version: '3.8'

services:
  web:
    build: ./web
    ports:
      - 5000:5000
    volumes:
      - ./web:/web
      - node_modules:/web/node_modules
    environment:
      PORT: 5000
      ESLINT_NO_DEV_ERRORS: "true"
  db:
    image: postgres:15.1
    # dont collide with existing postgres installation
    ports:
      - 127.0.0.1:5433:5432
    environment:
      POSTGRES_MULTIPLE_DATABASES: api_development,api_test
      POSTGRES_PASSWORD: secret
  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
    depends_on:
      - db
    # dont terminate docker after running bin/dev
    tty: true

volumes:
  node_modules:
