default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: secret
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  password: <%= ENV["DATABASE_URL"] %>
